import hashlib
import json
import unittest
from pathlib import Path

from spin8_mixed_monomial_golden_closure import certificate

ROOT = Path(__file__).resolve().parents[1]
ARTIFACT = ROOT / "artifacts" / "spin8_mixed_monomial_golden_closure_20260821.json"
EXPECTED_ARTIFACT_SHA256 = "21a5b6754002728bf89be19952fc0ae01994b70610b22768d8666c684d110e9c"


class Spin8MixedMonomialGoldenClosureTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.report = certificate()
        cls.stored = json.loads(ARTIFACT.read_text(encoding="utf-8"))

    def test_exact_replay_matches_artifact(self) -> None:
        self.assertEqual(self.report, self.stored)
        self.assertTrue(self.report["passed"])

    def test_short_mixed_word_proves_infinite_closure(self) -> None:
        conclusion = self.report["proved_conclusion"]
        self.assertEqual(
            conclusion["statement"],
            "the subgroup generated by the stated monomial normalizer generators and golden vector a,b is infinite",
        )
        gate = self.report["exact_cyclotomic_factor_gate"]
        self.assertEqual(
            gate["word"],
            "golden_vector_b*(fano_automorphism_b*(left_operator_e1))",
        )
        self.assertTrue(gate["has_non_cyclotomic_factor"])
        self.assertEqual(len(gate["non_cyclotomic_factors"]), 1)

    def test_bounded_search_and_orbit_boundary_are_preserved(self) -> None:
        enumeration = self.report["exact_bounded_enumeration"]
        self.assertEqual(enumeration["unique_matrices_total_by_depth"], [12, 119, 758])
        self.assertEqual(enumeration["unique_matrices_total"], 758)
        self.assertFalse(self.report["candidate_orbits"]["e0"]["closed_before_cap"])
        self.assertFalse(self.report["candidate_orbits"]["all_ones"]["closed_before_cap"])
        nonclaims = self.report["claim_scope"]["not_claimed"]
        self.assertIn(
            "a new group, a classification of the infinite subgroup, or density in SO(8)",
            nonclaims,
        )

    def test_mixed_representation_has_scalar_exact_commutant(self) -> None:
        diagnostics = self.report["exact_representation_diagnostics"]
        self.assertEqual(
            diagnostics["left_operator_commutant_dimension_over_qsqrt5"], 1
        )
        self.assertEqual(
            diagnostics["mixed_generator_commutant_dimension_over_qsqrt5"], 1
        )

    def test_artifact_hash(self) -> None:
        digest = hashlib.sha256(ARTIFACT.read_bytes()).hexdigest()
        self.assertEqual(digest, EXPECTED_ARTIFACT_SHA256)


if __name__ == "__main__":
    unittest.main()
