"""Exact finite groups behind the associative octonion-operator lift.

Raw unit octonions are nonassociative.  The maintained Spin(8) construction
instead represents left multiplication by signed permutation matrices.  Matrix
composition is associative, so the finite closure of the seven imaginary basis
operators is an honest group.  This module identifies that group and the larger
group obtained by adjoining every signed basis automorphism of the fixed Fano
multiplication table.

All calculations use integer signed permutations.  No floating-point tolerance
or stored artifact field participates in acceptance.
"""

from __future__ import annotations

import argparse
import hashlib
import itertools
import json
from collections import Counter
from collections.abc import Iterable
from pathlib import Path

import numpy as np

from spin8_triality import (
    FANO_TRIPLES,
    SPIN8_DIM,
    _octonion_multiplication_table,
    octonion_left_multiplication,
)

Monomial = tuple[int, ...]
Permutation = tuple[int, ...]


def identity_monomial(dimension: int = SPIN8_DIM) -> Monomial:
    """Encode the identity signed permutation by its column images."""

    return tuple(index + 1 for index in range(dimension))


def compose(left: Monomial, right: Monomial) -> Monomial:
    """Return ``left @ right`` for signed-permutation column encodings."""

    if len(left) != len(right):
        raise ValueError("signed permutations must have the same dimension")
    result = []
    for encoded in right:
        sign = 1 if encoded > 0 else -1
        image = left[abs(encoded) - 1]
        result.append(sign * image)
    return tuple(result)


def inverse(element: Monomial) -> Monomial:
    """Return the exact inverse signed permutation."""

    result = [0] * len(element)
    for source, encoded in enumerate(element):
        sign = 1 if encoded > 0 else -1
        target = abs(encoded) - 1
        result[target] = sign * (source + 1)
    return tuple(result)


def monomial_from_matrix(matrix: np.ndarray) -> Monomial:
    """Convert an exact integral monomial matrix to the compact encoding."""

    integral = np.asarray(matrix, dtype=np.int64)
    if integral.shape[0] != integral.shape[1]:
        raise ValueError("a monomial matrix must be square")
    if not np.array_equal(integral, np.asarray(matrix)):
        raise ValueError("matrix is not exactly integral")
    encoded = []
    used_rows = set()
    for column in range(integral.shape[1]):
        rows = np.flatnonzero(integral[:, column])
        if len(rows) != 1:
            raise ValueError("every column must have exactly one nonzero entry")
        row = int(rows[0])
        value = int(integral[row, column])
        if value not in (-1, 1) or row in used_rows:
            raise ValueError("matrix is not a signed permutation")
        used_rows.add(row)
        encoded.append(value * (row + 1))
    return tuple(encoded)


def matrix_from_monomial(element: Monomial) -> np.ndarray:
    """Expand a compact signed permutation to an integer matrix."""

    matrix = np.zeros((len(element), len(element)), dtype=np.int64)
    for column, encoded in enumerate(element):
        matrix[abs(encoded) - 1, column] = 1 if encoded > 0 else -1
    return matrix


def monomial_determinant(element: Monomial) -> int:
    """Return the determinant using sign parity only."""

    permutation = [abs(value) - 1 for value in element]
    inversions = sum(
        permutation[left] > permutation[right]
        for left in range(len(permutation))
        for right in range(left + 1, len(permutation))
    )
    entry_sign = np.prod([1 if value > 0 else -1 for value in element])
    return int(entry_sign) * (-1 if inversions % 2 else 1)


def closure(generators: Iterable[Monomial], *, maximum_order: int) -> set[Monomial]:
    """Enumerate the finite subgroup generated by signed permutations."""

    generators = tuple(dict.fromkeys(generators))
    if not generators:
        raise ValueError("at least one generator is required")
    dimension = len(generators[0])
    if any(len(generator) != dimension for generator in generators):
        raise ValueError("generator dimensions disagree")
    steps = tuple(dict.fromkeys((*generators, *(inverse(g) for g in generators))))
    identity = identity_monomial(dimension)
    reached = {identity}
    frontier = [identity]
    while frontier:
        current = frontier.pop()
        for step in steps:
            product = compose(current, step)
            if product in reached:
                continue
            reached.add(product)
            frontier.append(product)
            if len(reached) > maximum_order:
                raise RuntimeError(
                    f"generated closure exceeded the cap {maximum_order}"
                )
    return reached


def element_order(element: Monomial, *, maximum: int = 256) -> int:
    """Return the multiplicative order of one finite monomial element."""

    identity = identity_monomial(len(element))
    power = identity
    for order in range(1, maximum + 1):
        power = compose(power, element)
        if power == identity:
            return order
    raise RuntimeError(f"element order exceeds the search cap {maximum}")


def commutator(left: Monomial, right: Monomial) -> Monomial:
    """Return ``left^-1 right^-1 left right``."""

    return compose(compose(inverse(left), inverse(right)), compose(left, right))


def _element_order_distribution(group: set[Monomial]) -> dict[str, int]:
    return {
        str(order): count
        for order, count in sorted(Counter(element_order(g) for g in group).items())
    }


def _center(group: set[Monomial], generators: tuple[Monomial, ...]) -> set[Monomial]:
    return {
        element
        for element in group
        if all(compose(element, g) == compose(g, element) for g in generators)
    }


def _derived_subgroup(
    group: set[Monomial], generators: tuple[Monomial, ...]
) -> set[Monomial]:
    """Compute the normal closure of generator commutators."""

    normal_generators = {
        commutator(left, right) for left in generators for right in generators
    }
    while True:
        derived = closure(normal_generators, maximum_order=len(group))
        conjugates = {
            compose(compose(inverse(g), value), g)
            for value in normal_generators
            for g in generators
        }
        new_generators = conjugates - derived
        if not new_generators:
            return derived
        normal_generators.update(new_generators)


def _permutation_compose(left: Permutation, right: Permutation) -> Permutation:
    return tuple(left[value - 1] for value in right)


def _permutation_order(permutation: Permutation) -> int:
    identity = tuple(range(1, len(permutation) + 1))
    power = identity
    for order in range(1, 64):
        power = _permutation_compose(power, permutation)
        if power == identity:
            return order
    raise RuntimeError("permutation order exceeded the finite search cap")


def _permutation_closure(generators: tuple[Permutation, ...]) -> set[Permutation]:
    identity = tuple(range(1, len(generators[0]) + 1))
    reached = {identity}
    frontier = [identity]
    while frontier:
        current = frontier.pop()
        for generator in generators:
            product = _permutation_compose(current, generator)
            if product not in reached:
                reached.add(product)
                frontier.append(product)
    return reached


def _imaginary_projection(element: Monomial) -> Permutation:
    """Project an octonion-basis automorphism to its seven axes."""

    if element[0] != 1 or any(abs(value) == 1 for value in element[1:]):
        raise ValueError("element does not fix the real octonion basis vector")
    return tuple(abs(value) - 1 for value in element[1:])


def signed_basis_automorphisms() -> set[Monomial]:
    """Enumerate all signed basis maps preserving the fixed octonion product."""

    table = _octonion_multiplication_table()
    result: set[Monomial] = set()
    for permutation in itertools.permutations(range(1, SPIN8_DIM)):
        # First retain precisely the 168 incidence automorphisms of the Fano plane.
        if any(
            table[(permutation[first - 1], permutation[second - 1])][1]
            != permutation[third - 1]
            for first, second, third in FANO_TRIPLES
        ):
            continue
        for signs in itertools.product((-1, 1), repeat=SPIN8_DIM - 1):
            if any(
                signs[first - 1]
                * signs[second - 1]
                * table[(permutation[first - 1], permutation[second - 1])][0]
                != signs[third - 1]
                for first, second, third in FANO_TRIPLES
            ):
                continue
            element = (1,) + tuple(
                sign * (target + 1)
                for sign, target in zip(signs, permutation, strict=True)
            )
            # The seven oriented-line equations should imply all 64 products;
            # keep the exhaustive check as an independent acceptance gate.
            for left in range(SPIN8_DIM):
                left_sign = 1 if element[left] > 0 else -1
                left_image = abs(element[left]) - 1
                for right in range(SPIN8_DIM):
                    right_sign = 1 if element[right] > 0 else -1
                    right_image = abs(element[right]) - 1
                    source_sign, source_product = table[(left, right)]
                    image_sign, image_product = table[(left_image, right_image)]
                    lhs = source_sign * element[source_product]
                    rhs = left_sign * right_sign * image_sign * (image_product + 1)
                    if lhs != rhs:
                        raise AssertionError(
                            "line equations admitted a false automorphism"
                        )
            result.add(element)
    return result


def _projective_generating_pair(
    projections: set[Permutation],
) -> tuple[Permutation, Permutation]:
    order_two = sorted(p for p in projections if _permutation_order(p) == 2)
    order_three = sorted(p for p in projections if _permutation_order(p) == 3)
    for left in order_two:
        for right in order_three:
            if _permutation_order(_permutation_compose(left, right)) != 7:
                continue
            if len(_permutation_closure((left, right))) == 168:
                return left, right
    raise RuntimeError("the Fano permutation image lacks a (2,3,7) generating pair")


def _extension_split_diagnostic(
    automorphisms: set[Monomial], kernel: set[Monomial]
) -> dict[str, object]:
    lifts: dict[Permutation, list[Monomial]] = {}
    for element in automorphisms:
        lifts.setdefault(_imaginary_projection(element), []).append(element)
    first, second = _projective_generating_pair(set(lifts))
    generated_orders: Counter[int] = Counter()
    complement: tuple[Monomial, Monomial] | None = None
    full_pair: tuple[Monomial, Monomial] | None = None
    for left in sorted(lifts[first]):
        for right in sorted(lifts[second]):
            subgroup = closure((left, right), maximum_order=len(automorphisms))
            generated_orders[len(subgroup)] += 1
            if len(subgroup) == len(automorphisms) and full_pair is None:
                full_pair = (left, right)
            if len(subgroup) == 168 and subgroup.intersection(kernel) == {
                identity_monomial()
            }:
                complement = (left, right)
    return {
        "projective_generator_orders": [2, 3],
        "projective_product_order": 7,
        "projective_pair_generates_order": 168,
        "lift_pair_generated_order_distribution": {
            str(order): count for order, count in sorted(generated_orders.items())
        },
        "split_complement_found": complement is not None,
        "full_extension_generating_pair": (
            [list(full_pair[0]), list(full_pair[1])] if full_pair is not None else None
        ),
        "complement_generating_pair": (
            [list(complement[0]), list(complement[1])]
            if complement is not None
            else None
        ),
    }


def _operator_group_certificate() -> tuple[
    dict[str, object], set[Monomial], tuple[Monomial, ...]
]:
    rho_source = octonion_left_multiplication()
    rho_rounded = np.rint(rho_source)
    source_is_exactly_integral = np.array_equal(rho_source, rho_rounded)
    if not source_is_exactly_integral:
        raise ValueError("octonion basis operators are not exactly integral")
    rho = rho_rounded.astype(np.int64)
    generators = tuple(monomial_from_matrix(rho[index]) for index in range(1, 8))
    group = closure(generators, maximum_order=256)
    identity = identity_monomial()
    minus_identity = tuple(-value for value in identity)
    center = _center(group, generators)
    derived = _derived_subgroup(group, generators)
    squares = {compose(element, element) for element in group}
    commutators = {commutator(left, right) for left in group for right in group}
    square_identity_count = sum(compose(g, g) == identity for g in group)
    if square_identity_count == 72:
        extraspecial_type = "plus"
        structure = "2_+^(1+6)"
    elif square_identity_count == 56:
        extraspecial_type = "minus"
        structure = "2_-^(1+6)"
    else:
        extraspecial_type = "unclassified"
        structure = "unclassified"

    volume = identity
    for generator in generators:
        volume = compose(volume, generator)
    clifford_checks = []
    identity_matrix = np.eye(SPIN8_DIM, dtype=np.int64)
    for left, left_matrix in enumerate(rho[1:], start=1):
        for right, right_matrix in enumerate(rho[1:], start=1):
            target = -2 * int(left == right) * identity_matrix
            clifford_checks.append(
                np.array_equal(
                    left_matrix @ right_matrix + right_matrix @ left_matrix,
                    target,
                )
            )

    checks = {
        "source_operators_are_exactly_integral": source_is_exactly_integral,
        "order_is_128": len(group) == 128,
        "all_integral_signed_permutations": all(
            np.array_equal(
                matrix_from_monomial(element).T @ matrix_from_monomial(element),
                identity_matrix,
            )
            for element in group
        ),
        "clifford_relations": all(clifford_checks),
        "center_is_plus_minus_identity": center == {identity, minus_identity},
        "derived_is_plus_minus_identity": derived == {identity, minus_identity},
        "all_squares_are_central": squares <= center,
        "all_commutators_are_central": commutators <= center,
        "quotient_is_elementary_abelian_order_64": len(group) // len(center) == 64,
        "extraspecial_type_classified": extraspecial_type in {"plus", "minus"},
        "volume_relation_is_minus_identity": volume == minus_identity,
    }
    report = {
        "generator_count": len(generators),
        "order": len(group),
        "center_order": len(center),
        "derived_subgroup_order": len(derived),
        "square_set_order": len(squares),
        "commutator_set_order": len(commutators),
        "quotient_by_center_order": len(group) // len(center),
        "square_identity_count": square_identity_count,
        "extraspecial_type": extraspecial_type,
        "structure": structure,
        "element_order_distribution": _element_order_distribution(group),
        "ordered_volume_product": list(volume),
        "checks": checks,
        "passed": all(checks.values()),
    }
    return report, group, generators


def _automorphism_group_certificate() -> tuple[
    dict[str, object], set[Monomial], tuple[Monomial, ...]
]:
    automorphisms = signed_basis_automorphisms()
    identity = identity_monomial()
    projections = {_imaginary_projection(element) for element in automorphisms}
    kernel = {
        element
        for element in automorphisms
        if _imaginary_projection(element) == tuple(range(1, 8))
    }
    split = _extension_split_diagnostic(automorphisms, kernel)
    pair_payload = split["full_extension_generating_pair"]
    if pair_payload is None:
        raise RuntimeError("no two-generator lift generated the signed automorphisms")
    generators = tuple(tuple(int(value) for value in row) for row in pair_payload)
    generated = closure(generators, maximum_order=len(automorphisms))
    center = _center(automorphisms, generators)
    kernel_commutative = all(
        compose(left, right) == compose(right, left)
        for left in kernel
        for right in kernel
    )
    kernel_exponent_two = all(element_order(element) <= 2 for element in kernel)
    checks = {
        "signed_automorphism_order_is_1344": len(automorphisms) == 1344,
        "projected_fano_group_order_is_168": len(projections) == 168,
        "projection_kernel_order_is_8": len(kernel) == 8,
        "projection_kernel_is_elementary_abelian": (
            kernel_commutative and kernel_exponent_two
        ),
        "two_lifts_generate_full_group": generated == automorphisms,
        "center_is_trivial": center == {identity},
        "extension_split_status_resolved": not split["split_complement_found"],
    }
    report = {
        "order": len(automorphisms),
        "projected_fano_permutation_order": len(projections),
        "projection_kernel_order": len(kernel),
        "center_order": len(center),
        "extension": "2^3.PSL(2,7)",
        "extension_splits": bool(split["split_complement_found"]),
        "element_order_distribution": _element_order_distribution(automorphisms),
        "split_diagnostic": split,
        "checks": checks,
        "passed": all(checks.values()),
    }
    return report, automorphisms, generators


def _combined_extension_split_diagnostic(
    combined: set[Monomial],
    operator_group: set[Monomial],
    automorphism_group: set[Monomial],
) -> dict[str, object]:
    """Search every lift of one fixed (2,3,7) quotient generating pair."""

    projections = {_imaginary_projection(element) for element in automorphism_group}
    first, second = _projective_generating_pair(projections)
    quotient_labels: dict[Monomial, Permutation] = {}
    for automorphism in automorphism_group:
        projection = _imaginary_projection(automorphism)
        for operator in operator_group:
            element = compose(operator, automorphism)
            previous = quotient_labels.setdefault(element, projection)
            if previous != projection:
                raise AssertionError("operator coset received two quotient labels")
    if set(quotient_labels) != combined:
        raise AssertionError("operator-automorphism products did not cover the group")

    first_lifts = [
        element
        for element, projection in quotient_labels.items()
        if projection == first and element_order(element) == 2
    ]
    second_lifts = [
        element
        for element, projection in quotient_labels.items()
        if projection == second and element_order(element) == 3
    ]
    product_order_seven_pairs = 0
    hurwitz_relator_pairs = 0
    complement: tuple[Monomial, Monomial] | None = None
    for left in first_lifts:
        for right in second_lifts:
            if element_order(compose(left, right)) != 7:
                continue
            product_order_seven_pairs += 1
            if element_order(commutator(left, right)) != 4:
                continue
            hurwitz_relator_pairs += 1
            try:
                subgroup = closure((left, right), maximum_order=168)
            except RuntimeError:
                continue
            if (
                complement is None
                and len(subgroup) == 168
                and subgroup.intersection(operator_group) == {identity_monomial()}
            ):
                complement = (left, right)
    return {
        "quotient_generator_orders": [2, 3],
        "quotient_product_order": 7,
        "order_two_lifts": len(first_lifts),
        "order_three_lifts": len(second_lifts),
        "lift_pairs_with_product_order_seven": product_order_seven_pairs,
        "lift_pairs_with_commutator_order_four": hurwitz_relator_pairs,
        "split_complement_found": complement is not None,
        "complement_generating_pair": (
            [list(complement[0]), list(complement[1])]
            if complement is not None
            else None
        ),
    }


def _normalizer_certificate(
    operator_report: dict[str, object],
    operator_group: set[Monomial],
    operator_generators: tuple[Monomial, ...],
    automorphism_group: set[Monomial],
    automorphism_generators: tuple[Monomial, ...],
) -> dict[str, object]:
    generators = (*operator_generators, *automorphism_generators)
    combined = closure(generators, maximum_order=21504)
    identity = identity_monomial()
    minus_identity = tuple(-value for value in identity)
    intersection = operator_group.intersection(automorphism_group)
    normalized = all(
        compose(compose(automorphism, generator), inverse(automorphism))
        in operator_group
        for automorphism in automorphism_generators
        for generator in operator_generators
    )
    center = _center(combined, generators)
    derived = _derived_subgroup(combined, generators)
    orbit = {(1 if element[0] > 0 else -1) * abs(element[0]) for element in combined}
    determinant_distribution = Counter(
        monomial_determinant(element) for element in combined
    )
    expected_order = len(operator_group) * len(automorphism_group) // len(intersection)
    split = _combined_extension_split_diagnostic(
        combined, operator_group, automorphism_group
    )
    checks = {
        "automorphisms_normalize_operator_group": normalized,
        "intersection_order_is_8": len(intersection) == 8,
        "product_formula_order_is_21504": expected_order == 21504,
        "generated_order_matches_product_formula": len(combined) == expected_order,
        "operator_group_is_normal": all(
            compose(compose(g, operator), inverse(g)) in operator_group
            for g in generators
            for operator in operator_generators
        ),
        "quotient_by_operator_group_has_order_168": (
            len(combined) // len(operator_group) == 168
        ),
        "center_is_plus_minus_identity": center == {identity, minus_identity},
        "derived_subgroup_is_whole_group": derived == combined,
        "acts_transitively_on_signed_basis_units": len(orbit) == 16,
        "orientation_preserving": determinant_distribution == Counter({1: 21504}),
        "extension_splits": bool(split["split_complement_found"]),
    }
    return {
        "order": len(combined),
        "operator_normal_subgroup_order": len(operator_group),
        "signed_automorphism_subgroup_order": len(automorphism_group),
        "intersection_order": len(intersection),
        "quotient_by_operator_group_order": len(combined) // len(operator_group),
        "center_order": len(center),
        "derived_subgroup_order": len(derived),
        "signed_basis_unit_orbit_order": len(orbit),
        "determinant_distribution": {
            str(value): count
            for value, count in sorted(determinant_distribution.items())
        },
        "structure": (
            f"{operator_report['structure']}"
            f"{':' if split['split_complement_found'] else '.'}PSL(2,7)"
        ),
        "extension_splits": bool(split["split_complement_found"]),
        "split_diagnostic": split,
        "checks": checks,
        "passed": all(checks.values()),
    }


def certificate() -> dict[str, object]:
    """Build the complete exact group-classification report."""

    operator_report, operator_group, operator_generators = _operator_group_certificate()
    automorphism_report, automorphism_group, automorphism_generators = (
        _automorphism_group_certificate()
    )
    normalizer_report = _normalizer_certificate(
        operator_report,
        operator_group,
        operator_generators,
        automorphism_group,
        automorphism_generators,
    )
    passed = bool(
        operator_report["passed"]
        and automorphism_report["passed"]
        and normalizer_report["passed"]
    )
    payload = {
        "schema_version": 1,
        "experiment": "exact finite groups of the associative octonion-operator lift",
        "basis_convention": {
            "fano_triples": [list(triple) for triple in FANO_TRIPLES],
            "operator": "rho_i is left multiplication by imaginary basis unit e_i",
            "composition": "ordinary associative 8x8 integer matrix multiplication",
        },
        "left_operator_group": operator_report,
        "signed_basis_automorphism_group": automorphism_report,
        "generated_operator_normalizer": normalizer_report,
        "claim_scope": {
            "proved_exactly": [
                "the seven left basis operators generate the stated extraspecial group",
                "the complete signed Fano-basis automorphism extension and split status",
                "the generated 21,504-element associative matrix group and its listed invariants",
            ],
            "not_claimed": [
                "that any abstract group in this report was previously unknown",
                "a classification of all finite subgroups of Spin(8) or G2",
                "a new simple group",
                "an ML-quality or kernel-speed advantage",
            ],
        },
        "passed": passed,
    }
    canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"))
    payload["certificate_sha256_without_self_hash"] = hashlib.sha256(
        canonical.encode("utf-8")
    ).hexdigest()
    return payload


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path)
    return parser.parse_args()


def main() -> int:
    arguments = _parse_args()
    report = certificate()
    encoded = json.dumps(report, indent=2, sort_keys=True) + "\n"
    if arguments.output is not None:
        arguments.output.parent.mkdir(parents=True, exist_ok=True)
        arguments.output.write_text(encoded, encoding="utf-8")
    print(encoded, end="")
    return 0 if report["passed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
