"""Modular reconstruction of the full Spin(9) Grassmann V5 determinant.

The V5 normal slice at the Cayley-null three-plane is the spin-two module
``Sym_0(3)``.  A two-dimensional Cartan section has coordinates ``(u, v)``.
The invariant ring on that section is generated by

``p = 3*u**2 + v**2`` and ``y = sqrt(2)*u*(v**2 - u**2)``.

For the graph projector based at the Cayley-null plane, the information
determinant ratio has the form

``N(p, y) / (1 + 8*p + 20*p**2 + 16*p**3 - 16*y**2)**14``.

This module reconstructs the 631 rational coefficients of the weighted-degree
84 numerator.  Determinants are evaluated over several prime fields where 2
is a square.  Scaling lines reduce the interpolation to univariate degree 84;
the remaining direction interpolation uses the invariant basis directly.

The reconstruction and independent-prime validation are exact modular
computations.  Promoting the resulting polynomial to a theorem still requires
an exact characteristic-zero identity check or a declared coefficient bound.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from dataclasses import dataclass
from fractions import Fraction
from pathlib import Path

import numpy as np
import sympy as sp

from spin9_dirac_clifford import (
    _modular_determinant,
    build_spin9_clifford_system,
)

WEIGHTED_DEGREE = 84
SCALE_NODES = 85
DIRECTION_COUNT = 30
IDENTITY_WEIGHTED_DEGREE = 216
IDENTITY_SCALE_NODES = IDENTITY_WEIGHTED_DEGREE + 1
IDENTITY_DIRECTION_COUNT = 40

RECONSTRUCTION_PRIMES = (
    90_000_049,
    90_000_073,
    90_000_089,
    90_000_103,
    90_000_121,
    90_000_217,
    90_000_233,
    90_000_241,
    90_000_257,
    90_000_343,
    90_000_377,
    90_000_401,
)
IDENTITY_PRIMES = RECONSTRUCTION_PRIMES + (
    90_000_433,
    90_000_439,
    90_000_479,
    90_000_551,
    90_000_553,
    90_000_583,
    90_000_607,
    90_000_697,
)
VALIDATION_PRIME = 90_000_767

MONOMIALS = tuple(
    (a, b)
    for b in range(WEIGHTED_DEGREE // 3 + 1)
    for a in range(WEIGHTED_DEGREE // 2 + 1)
    if 2 * a + 3 * b <= WEIGHTED_DEGREE
)
MONOMIAL_INDEX = {monomial: index for index, monomial in enumerate(MONOMIALS)}
MONOMIALS_BY_WEIGHT = {
    degree: tuple(
        monomial
        for monomial in MONOMIALS
        if 2 * monomial[0] + 3 * monomial[1] == degree
    )
    for degree in range(WEIGHTED_DEGREE + 1)
}
IDENTITY_MONOMIALS_BY_WEIGHT = {
    degree: tuple(
        (a, b)
        for b in range(IDENTITY_WEIGHTED_DEGREE // 3 + 1)
        for a in range(IDENTITY_WEIGHTED_DEGREE // 2 + 1)
        if 2 * a + 3 * b == degree
    )
    for degree in range(IDENTITY_WEIGHTED_DEGREE + 1)
}


@dataclass(frozen=True)
class ModularCartanSystem:
    """Prime-field matrices needed for determinant evaluation."""

    prime: int
    sqrt2: int
    generators: np.ndarray
    frame: np.ndarray
    axis: np.ndarray
    transverse: np.ndarray
    inverse_base_determinant: int


def _modular_inverse(matrix: np.ndarray, prime: int) -> np.ndarray:
    """Return the exact inverse of a square matrix over F_p."""

    work = np.remainder(matrix, prime).astype(np.int64)
    size = work.shape[0]
    augmented = np.concatenate([work, np.eye(size, dtype=np.int64)], axis=1)
    for column in range(size):
        candidates = np.flatnonzero(augmented[column:, column])
        if candidates.size == 0:
            raise ValueError(f"singular modular matrix at column {column}")
        pivot = column + int(candidates[0])
        if pivot != column:
            augmented[[column, pivot]] = augmented[[pivot, column]]
        inverse = pow(int(augmented[column, column]), -1, prime)
        augmented[column] = np.remainder(augmented[column] * inverse, prime)
        active = np.flatnonzero(augmented[:, column])
        active = active[active != column]
        if active.size:
            augmented[active] = np.remainder(
                augmented[active] - augmented[active, column, None] * augmented[column],
                prime,
            )
    return augmented[:, size:]


def _independent_rows(matrix: np.ndarray, prime: int) -> list[int]:
    """Return row indices spanning the column space over F_p."""

    work = np.remainder(matrix.T, prime).astype(np.int64)
    rank = 0
    pivot_columns: list[int] = []
    for column in range(work.shape[1]):
        candidates = np.flatnonzero(work[rank:, column])
        if candidates.size == 0:
            continue
        pivot = rank + int(candidates[0])
        if pivot != rank:
            work[[rank, pivot]] = work[[pivot, rank]]
        inverse = pow(int(work[rank, column]), -1, prime)
        work[rank] = np.remainder(work[rank] * inverse, prime)
        active = np.flatnonzero(work[:, column])
        active = active[active != rank]
        if active.size:
            work[active] = np.remainder(
                work[active] - work[active, column, None] * work[rank],
                prime,
            )
        pivot_columns.append(column)
        rank += 1
        if rank == work.shape[0]:
            break
    return pivot_columns


def _adjugate_and_determinant(matrix: np.ndarray, prime: int) -> tuple[np.ndarray, int]:
    """Return the adjugate and determinant of a 3-by-3 matrix over F_p."""

    a, b, c = (int(value) for value in matrix[0])
    d, e, f = (int(value) for value in matrix[1])
    g, h, i = (int(value) for value in matrix[2])
    aa = (e * i - f * h) % prime
    ab = (c * h - b * i) % prime
    ac = (b * f - c * e) % prime
    ba = (f * g - d * i) % prime
    bb = (a * i - c * g) % prime
    bc = (c * d - a * f) % prime
    ca = (d * h - e * g) % prime
    cb = (b * g - a * h) % prime
    cc = (a * e - b * d) % prime
    adjugate = np.asarray([[aa, ab, ac], [ba, bb, bc], [ca, cb, cc]], dtype=np.int64)
    determinant = (a * aa + b * ba + c * ca) % prime
    return adjugate, determinant


def _raw_matrices(prime: int, sqrt2: int) -> tuple[np.ndarray, ...]:
    """Build the Clifford generators, base frame, and Cartan variations."""

    inverse_two = pow(2, -1, prime)
    system = build_spin9_clifford_system()
    generators = np.remainder(system.doubled_spin_generators, prime).astype(np.int64)

    frame = np.zeros((16, 3), dtype=np.int64)
    frame[0, 0] = 1
    frame[1, 1] = sqrt2 * inverse_two % prime
    frame[8, 1] = sqrt2 * inverse_two % prime
    frame[2, 2] = -sqrt2 * inverse_two % prime
    frame[12, 2] = sqrt2 * inverse_two % prime
    frame = np.remainder(frame, prime)

    axis = np.zeros((16, 3), dtype=np.int64)
    for row, column, value in (
        (1, 1, 2),
        (2, 2, 1),
        (5, 2, -1),
        (6, 1, -1),
        (8, 1, -2),
        (9, 0, -2 * sqrt2),
        (11, 2, -1),
        (12, 2, 1),
        (14, 0, sqrt2),
        (15, 1, 1),
    ):
        axis[row, column] = value % prime

    transverse = np.zeros((16, 3), dtype=np.int64)
    for row, column, value in (
        (4, 2, -sqrt2),
        (6, 0, -1),
        (10, 2, sqrt2),
        (14, 1, sqrt2),
        (15, 0, 1),
    ):
        transverse[row, column] = value % prime
    return generators, frame, axis, transverse


def _information_numerator(
    system: ModularCartanSystem,
    u_value: int,
    v_value: int,
) -> tuple[np.ndarray, int]:
    """Return ``J = delta*I`` and the Gram determinant over F_p."""

    prime = system.prime
    frame = np.remainder(
        system.frame + u_value * system.axis + v_value * system.transverse,
        prime,
    )
    gram = np.remainder(frame.T @ frame, prime)
    adjugate, gram_determinant = _adjugate_and_determinant(gram, prime)

    observations = np.remainder(
        np.einsum("gij,jc->cgi", system.generators, frame, optimize=True),
        prime,
    )
    information_numerator = np.zeros((36, 36), dtype=np.int64)
    for left in range(3):
        for right in range(3):
            contribution = np.remainder(
                observations[left] @ observations[right].T, prime
            )
            information_numerator = np.remainder(
                information_numerator + int(adjugate[left, right]) * contribution,
                prime,
            )
    return information_numerator, gram_determinant


def _raw_information_determinant(
    system: ModularCartanSystem,
    u_value: int,
    v_value: int,
) -> int:
    """Evaluate the polynomial determinant ``det(J(u,v))`` over F_p."""

    information_numerator, _ = _information_numerator(system, u_value, v_value)
    return _modular_determinant(information_numerator, system.prime)


def _determinant_numerator_value(
    system: ModularCartanSystem,
    scale: int,
    direction: int,
) -> int | None:
    """Evaluate N on ``(u,v)=(scale,direction*scale)`` over F_p."""

    information_numerator, gram_determinant = _information_numerator(
        system,
        scale,
        direction * scale,
    )
    if gram_determinant == 0:
        return None
    prime = system.prime
    determinant = _modular_determinant(information_numerator, prime)
    # det(I)/det(I_0) = det(J)/(det(J_0) * delta^36), while the
    # reduced invariant form is N/delta^14.
    return (
        determinant
        * system.inverse_base_determinant
        * pow(gram_determinant, -22, prime)
    ) % prime


def _build_modular_system(
    prime: int,
    *,
    sqrt2: int | None = None,
) -> ModularCartanSystem:
    """Construct one prime-field evaluation system."""

    if sqrt2 is None:
        sqrt2 = int(sp.sqrt_mod(2, prime))
    if sqrt2 * sqrt2 % prime != 2:
        raise ValueError(
            f"the supplied value is not a square root of two modulo {prime}"
        )
    generators, frame, axis, transverse = _raw_matrices(prime, sqrt2)
    provisional = ModularCartanSystem(
        prime=prime,
        sqrt2=sqrt2,
        generators=generators,
        frame=frame,
        axis=axis,
        transverse=transverse,
        inverse_base_determinant=1,
    )
    # At scale zero, the Gram determinant is one, so the returned numerator
    # value is the unnormalized information determinant.
    base_value = _determinant_numerator_value(provisional, 0, 0)
    if base_value in (None, 0):
        raise ValueError(f"singular base information modulo {prime}")
    return ModularCartanSystem(
        prime=prime,
        sqrt2=sqrt2,
        generators=generators,
        frame=frame,
        axis=axis,
        transverse=transverse,
        inverse_base_determinant=pow(int(base_value), -1, prime),
    )


def _safe_scale_nodes(system: ModularCartanSystem) -> list[int]:
    """Choose 85 scale nodes avoiding every selected direction pole."""

    nodes: list[int] = []
    candidate = 0
    while len(nodes) < SCALE_NODES:
        valid = True
        for direction in range(DIRECTION_COUNT):
            p_value = (
                (3 + direction * direction) * candidate * candidate
            ) % system.prime
            y_value = (
                system.sqrt2
                * (direction * direction - 1)
                * pow(candidate, 3, system.prime)
            ) % system.prime
            delta = (
                1 + 8 * p_value + 20 * p_value**2 + 16 * p_value**3 - 16 * y_value**2
            ) % system.prime
            if delta == 0:
                valid = False
                break
        if valid:
            nodes.append(candidate)
        candidate += 1
    return nodes


def reconstruct_mod_prime(prime: int) -> tuple[int, ...]:
    """Reconstruct all invariant numerator coefficients modulo one prime."""

    system = _build_modular_system(prime)
    nodes = _safe_scale_nodes(system)
    vandermonde = np.asarray(
        [[pow(node, degree, prime) for degree in range(SCALE_NODES)] for node in nodes],
        dtype=np.int64,
    )
    vandermonde_inverse = _modular_inverse(vandermonde, prime)

    values = np.empty((DIRECTION_COUNT, SCALE_NODES), dtype=np.int64)
    for direction in range(DIRECTION_COUNT):
        for index, scale in enumerate(nodes):
            value = _determinant_numerator_value(system, scale, direction)
            if value is None:
                raise AssertionError("safe-node selection admitted a pole")
            values[direction, index] = value
    line_coefficients = np.remainder(vandermonde_inverse @ values.T, prime).T

    result = [0] * len(MONOMIALS)
    for degree, monomials in MONOMIALS_BY_WEIGHT.items():
        if not monomials:
            continue
        direction_matrix = np.asarray(
            [
                [
                    pow((3 + direction * direction) % prime, a, prime)
                    * pow(
                        system.sqrt2 * (direction * direction - 1) % prime,
                        b,
                        prime,
                    )
                    % prime
                    for a, b in monomials
                ]
                for direction in range(DIRECTION_COUNT)
            ],
            dtype=np.int64,
        )
        pivot_rows = _independent_rows(direction_matrix, prime)
        if len(pivot_rows) != len(monomials):
            raise ValueError(f"direction interpolation rank loss at weight {degree}")
        square = direction_matrix[pivot_rows]
        right = line_coefficients[pivot_rows, degree]
        coefficients = np.remainder(_modular_inverse(square, prime) @ right, prime)
        for monomial, coefficient in zip(monomials, coefficients, strict=True):
            result[MONOMIAL_INDEX[monomial]] = int(coefficient)

    # All unused direction rows are exact holdouts for every weight.
    for direction in range(DIRECTION_COUNT):
        p_direction = (3 + direction * direction) % prime
        y_direction = (system.sqrt2 * (direction * direction - 1)) % prime
        for degree, monomials in MONOMIALS_BY_WEIGHT.items():
            predicted = (
                sum(
                    result[MONOMIAL_INDEX[(a, b)]]
                    * pow(p_direction, a, prime)
                    * pow(y_direction, b, prime)
                    for a, b in monomials
                )
                % prime
            )
            if predicted != int(line_coefficients[direction, degree]):
                raise AssertionError(
                    f"direction holdout failed at ({direction}, {degree})"
                )
    return tuple(result)


def _rational_reconstruction(value: int, modulus: int) -> Fraction | None:
    """Wang rational reconstruction with the standard sqrt(modulus/2) bound."""

    value %= modulus
    r0, s0 = modulus, 0
    r1, s1 = value, 1
    bound = sp.integer_nthroot(modulus // 2, 2)[0]
    while r1 >= bound:
        quotient = r0 // r1
        r0, r1 = r1, r0 - quotient * r1
        s0, s1 = s1, s0 - quotient * s1
    if s1 == 0 or abs(s1) >= bound:
        return None
    if s1 < 0:
        r1, s1 = -r1, -s1
    return Fraction(r1, s1)


def reconstruct_rational_coefficients(
    primes: tuple[int, ...] = RECONSTRUCTION_PRIMES,
) -> tuple[tuple[Fraction, ...], int]:
    """CRT-combine prime images and recover the rational coefficients."""

    combined = [0] * len(MONOMIALS)
    modulus = 1
    for prime in primes:
        residues = reconstruct_mod_prime(prime)
        correction_inverse = pow(modulus % prime, -1, prime)
        for index, residue in enumerate(residues):
            correction = (
                (residue - combined[index]) % prime * correction_inverse
            ) % prime
            combined[index] += modulus * correction
        modulus *= prime

    rational = tuple(_rational_reconstruction(value, modulus) for value in combined)
    if any(value is None for value in rational):
        missing = sum(value is None for value in rational)
        raise ValueError(
            f"{missing} coefficients exceed the rational reconstruction bound"
        )
    return tuple(value for value in rational if value is not None), modulus


def validate_rational_coefficients(
    coefficients: tuple[Fraction, ...],
    prime: int = VALIDATION_PRIME,
) -> bool:
    """Check a reconstructed coefficient vector at an unused prime."""

    expected = reconstruct_mod_prime(prime)
    recovered = tuple(
        coefficient.numerator * pow(coefficient.denominator, -1, prime) % prime
        for coefficient in coefficients
    )
    return recovered == expected


def _evaluate_invariant_numerator(
    coefficients: tuple[Fraction, ...],
    p_value: int,
    y_value: int,
    prime: int,
) -> int:
    """Evaluate the reconstructed invariant numerator over F_p."""

    p_powers = [1]
    for _ in range(max(a for a, _ in MONOMIALS)):
        p_powers.append(p_powers[-1] * p_value % prime)
    y_powers = [1]
    for _ in range(max(b for _, b in MONOMIALS)):
        y_powers.append(y_powers[-1] * y_value % prime)
    value = 0
    for (a, b), coefficient in zip(MONOMIALS, coefficients, strict=True):
        residue = (
            coefficient.numerator * pow(coefficient.denominator, -1, prime) % prime
        )
        value = (value + residue * p_powers[a] * y_powers[b]) % prime
    return value


def _invariant_line_coefficients(
    coefficients: tuple[Fraction, ...],
    direction: int,
    system: ModularCartanSystem,
) -> tuple[int, ...]:
    """Restrict ``N`` to ``(u,v)=(scale,direction*scale)`` over F_p."""

    prime = system.prime
    p_direction = (3 + direction * direction) % prime
    y_direction = (system.sqrt2 * (direction * direction - 1)) % prime
    result = [0] * (WEIGHTED_DEGREE + 1)
    for (a, b), coefficient in zip(MONOMIALS, coefficients, strict=True):
        degree = 2 * a + 3 * b
        residue = (
            coefficient.numerator * pow(coefficient.denominator, -1, prime) % prime
        )
        result[degree] = (
            result[degree]
            + residue * pow(p_direction, a, prime) * pow(y_direction, b, prime)
        ) % prime
    return tuple(result)


def _identity_direction_rank_check(system: ModularCartanSystem) -> None:
    """Check that the selected directions separate every invariant weight."""

    prime = system.prime
    for degree, monomials in IDENTITY_MONOMIALS_BY_WEIGHT.items():
        if not monomials:
            continue
        matrix = np.asarray(
            [
                [
                    pow((3 + direction * direction) % prime, a, prime)
                    * pow(
                        system.sqrt2 * (direction * direction - 1) % prime,
                        b,
                        prime,
                    )
                    % prime
                    for a, b in monomials
                ]
                for direction in range(IDENTITY_DIRECTION_COUNT)
            ],
            dtype=np.int64,
        )
        if len(_independent_rows(matrix, prime)) != len(monomials):
            raise AssertionError(f"identity direction rank loss at weight {degree}")


def validate_polynomial_identity_mod_prime(
    coefficients: tuple[Fraction, ...],
    prime: int,
) -> bool:
    """Prove ``det(J)=det(J0)*delta**22*N`` over both roots in F_p.

    Both sides have total degree at most 216 and are invariants of the spin-two
    module.  The 40 directions separate the invariant monomials at every
    weight, while 217 scale values determine each restricted polynomial.
    """

    positive_root = int(sp.sqrt_mod(2, prime))
    for root in (positive_root, (-positive_root) % prime):
        system = _build_modular_system(prime, sqrt2=root)
        _identity_direction_rank_check(system)
        base_determinant = pow(system.inverse_base_determinant, -1, prime)
        for direction in range(IDENTITY_DIRECTION_COUNT):
            line_coefficients = _invariant_line_coefficients(
                coefficients,
                direction,
                system,
            )
            for scale in range(IDENTITY_SCALE_NODES):
                u_value = scale
                v_value = direction * scale
                raw_determinant = _raw_information_determinant(
                    system,
                    u_value,
                    v_value,
                )
                p_value = (3 * u_value**2 + v_value**2) % prime
                y_value = (system.sqrt2 * u_value * (v_value**2 - u_value**2)) % prime
                delta = (
                    1
                    + 8 * p_value
                    + 20 * p_value**2
                    + 16 * p_value**3
                    - 16 * y_value**2
                ) % prime
                numerator = 0
                for coefficient in reversed(line_coefficients):
                    numerator = (numerator * scale + coefficient) % prime
                expected = (
                    base_determinant * pow(delta, 22, prime) * numerator
                ) % prime
                if raw_determinant != expected:
                    return False
    return True


def numerator_polynomial(
    coefficients: tuple[Fraction, ...],
) -> sp.Poly:
    """Return N(p,y) as an exact SymPy polynomial."""

    p, y = sp.symbols("p y", real=True)
    expression = sum(
        sp.Rational(coefficient.numerator, coefficient.denominator) * p**a * y**b
        for (a, b), coefficient in zip(MONOMIALS, coefficients, strict=True)
    )
    return sp.Poly(expression, p, y, domain=sp.QQ)


def coefficient_payload(
    coefficients: tuple[Fraction, ...],
    modulus: int,
) -> dict[str, object]:
    """Return the auditable JSON payload for a recovered numerator."""

    rows = [
        {
            "p_power": a,
            "y_power": b,
            "coefficient": str(coefficient),
        }
        for (a, b), coefficient in zip(MONOMIALS, coefficients, strict=True)
    ]
    canonical = "\n".join(
        f"{row['p_power']},{row['y_power']}:{row['coefficient']}" for row in rows
    )
    unused_prime_valid = validate_rational_coefficients(coefficients)
    return {
        "schema_version": 1,
        "claim_scope": "modular reconstruction of the full V5 Cartan determinant numerator",
        "invariants": {
            "p": "3*u^2 + v^2",
            "y": "sqrt(2)*u*(v^2-u^2)",
            "gram_determinant": "1 + 8*p + 20*p^2 + 16*p^3 - 16*y^2",
            "determinant_ratio_form": "N(p,y)/gram_determinant^14",
        },
        "weighted_degree": WEIGHTED_DEGREE,
        "coefficient_count": len(coefficients),
        "nonzero_coefficient_count": sum(value != 0 for value in coefficients),
        "all_coefficients_integral": all(
            value.denominator == 1 for value in coefficients
        ),
        "maximum_numerator_digits": max(
            len(str(abs(value.numerator))) for value in coefficients
        ),
        "reconstruction_primes": list(RECONSTRUCTION_PRIMES),
        "crt_modulus": str(modulus),
        "crt_modulus_decimal_digits": len(str(modulus)),
        "unused_validation_prime": VALIDATION_PRIME,
        "unused_prime_validation_passed": unused_prime_valid,
        "coefficient_rows_sha256": hashlib.sha256(canonical.encode()).hexdigest(),
        "coefficients": rows,
        "characteristic_zero_identity_certified": False,
        "passed": bool(unused_prime_valid),
    }


def load_coefficients(path: Path) -> tuple[Fraction, ...]:
    """Load and validate a generated coefficient artifact."""

    payload = json.loads(path.read_text(encoding="utf-8"))
    rows = payload["coefficients"]
    if len(rows) != len(MONOMIALS):
        raise ValueError("coefficient artifact has the wrong row count")
    result: list[Fraction] = []
    canonical_rows: list[str] = []
    for monomial, row in zip(MONOMIALS, rows, strict=True):
        if (row["p_power"], row["y_power"]) != monomial:
            raise ValueError("coefficient artifact monomial order mismatch")
        value = Fraction(row["coefficient"])
        result.append(value)
        canonical_rows.append(f"{row['p_power']},{row['y_power']}:{row['coefficient']}")
    digest = hashlib.sha256("\n".join(canonical_rows).encode()).hexdigest()
    if digest != payload["coefficient_rows_sha256"]:
        raise ValueError("coefficient artifact digest mismatch")
    return tuple(result)


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, help="optional reconstruction JSON path")
    return parser.parse_args()


def main() -> int:
    args = _parse_args()
    coefficients, modulus = reconstruct_rational_coefficients()
    payload = coefficient_payload(coefficients, modulus)
    encoded = json.dumps(payload, indent=2, sort_keys=True)
    if args.output is not None:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(encoded + "\n", encoding="utf-8")
    print(encoded)
    return 0 if payload["passed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
