"""Modular reconstruction on the coupled Spin(9) Grassmann V1+V5 slice.

At the Cayley-null plane, the six-dimensional Grassmann normal slice is the
sum of a trivial line V1 and the spin-two module V5. In Cartan coordinates
(s,u,v), a rational invariant basis is generated by x=sqrt(2)*s,
p=3*u**2+v**2, and y=sqrt(2)*u*(v**2-u**2), of weights one, two, and three.

This module reconstructs all 18,600 coefficients of a weighted-degree-84
candidate numerator N(x,p,y). It is an exact prime-field reconstruction with
unused-prime and special-boundary checks, but deliberately not a
characteristic-zero identity or global positivity certificate.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import random
import sys
from concurrent.futures import ProcessPoolExecutor
from dataclasses import dataclass
from fractions import Fraction
from pathlib import Path

import numpy as np

from spin9_dirac_clifford import _modular_determinant
from spin9_v5_cartan_reconstruction import (
    MONOMIALS,
    RECONSTRUCTION_PRIMES,
    VALIDATION_PRIME,
    WEIGHTED_DEGREE,
    ModularCartanSystem,
    _adjugate_and_determinant,
    _build_modular_system,
    _modular_inverse,
    _rational_reconstruction,
)
from spin9_v5_cartan_reconstruction import load_coefficients as load_v5_coefficients

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_V5_ARTIFACT = (
    ROOT / "artifacts" / "spin9_v5_cartan_reconstruction_20260811.json"
)

SCALE_NODE_COUNT = WEIGHTED_DEGREE + 1
RECONSTRUCTION_DIRECTION_COUNT = len(MONOMIALS)
HOLDOUT_DIRECTION_COUNT = 10
DIRECTION_SEED = 20_260_811

COUPLED_MONOMIALS = tuple(
    (weight - 2 * a - 3 * b, a, b)
    for weight in range(WEIGHTED_DEGREE + 1)
    for a, b in MONOMIALS
    if 2 * a + 3 * b <= weight
)

COUPLED_INFORMATION_BLOCKS = (
    (0, 5, 6, 7, 12, 13, 14, 15, 16, 17, 21, 22, 26, 33, 34, 35),
    (1, 2, 3, 4, 8, 9, 10, 11, 18, 19, 20, 23, 24, 25, 27, 28, 29, 30, 31, 32),
)


@dataclass(frozen=True)
class CoupledModularSystem:
    """Prime-field data for the coupled normal slice."""

    cartan: ModularCartanSystem
    scalar: np.ndarray
    inverse_base_block_determinants: tuple[int, int]


def _scalar_variation(prime: int, sqrt2: int) -> np.ndarray:
    result = np.zeros((16, 3), dtype=np.int64)
    for row, column, value in (
        (1, 1, 1),
        (2, 2, -1),
        (5, 2, 1),
        (6, 1, 1),
        (8, 1, -1),
        (9, 0, -sqrt2),
        (11, 2, 1),
        (12, 2, -1),
        (14, 0, -sqrt2),
        (15, 1, -1),
    ):
        result[row, column] = value % prime
    return result


def _build_coupled_system(
    prime: int,
    *,
    sqrt2: int | None = None,
) -> CoupledModularSystem:
    cartan = _build_modular_system(prime, sqrt2=sqrt2)
    base_block_determinants, base_gram_determinant = _block_determinants(
        cartan,
        cartan.frame,
    )
    if base_gram_determinant != 1:
        raise AssertionError("maintained Cayley-null frame lost orthonormality")
    return CoupledModularSystem(
        cartan=cartan,
        scalar=_scalar_variation(prime, cartan.sqrt2),
        inverse_base_block_determinants=tuple(
            pow(value, -1, prime) for value in base_block_determinants
        ),
    )


def _block_determinants(
    cartan: ModularCartanSystem,
    frame: np.ndarray,
) -> tuple[tuple[int, int], int]:
    """Return the raw 16- and 20-block determinants and Gram determinant."""

    prime = cartan.prime
    gram = np.remainder(frame.T @ frame, prime)
    adjugate, gram_determinant = _adjugate_and_determinant(gram, prime)
    if gram_determinant == 0:
        return (0, 0), 0

    observations = np.remainder(
        np.einsum("gij,jc->cgi", cartan.generators, frame, optimize=True),
        prime,
    )
    information_numerator = np.zeros((36, 36), dtype=np.int64)
    for left in range(3):
        for right in range(3):
            contribution = np.remainder(
                observations[left] @ observations[right].T,
                prime,
            )
            information_numerator = np.remainder(
                information_numerator + int(adjugate[left, right]) * contribution,
                prime,
            )
    determinants = tuple(
        _modular_determinant(
            information_numerator[np.ix_(block, block)],
            prime,
        )
        for block in COUPLED_INFORMATION_BLOCKS
    )
    return determinants, gram_determinant


def _coupled_delta(
    x_value: int,
    p_value: int,
    y_value: int,
    system: CoupledModularSystem,
) -> int:
    """Evaluate the exact coupled Gram determinant in rational invariants."""

    prime = system.cartan.prime
    x_value %= prime
    p_value %= prime
    y_value %= prime
    return (
        1
        + 8 * p_value
        + 20 * p_value**2
        + 16 * p_value**3
        - 16 * y_value**2
        + 6 * x_value**2
        + 24 * x_value**2 * p_value
        + 8 * x_value**2 * p_value**2
        + 12 * x_value**4
        + 16 * x_value**4 * p_value
        + 8 * x_value**6
        + 24 * x_value * y_value
        + 80 * x_value * p_value * y_value
        + 80 * x_value**3 * y_value
    ) % prime


def _coupled_numerator_value(
    system: CoupledModularSystem,
    s_value: int,
    u_value: int,
    v_value: int,
) -> int | None:
    """Evaluate the candidate numerator at the raw scalar coordinate s."""

    cartan = system.cartan
    prime = cartan.prime
    frame = np.remainder(
        cartan.frame
        + s_value * system.scalar
        + u_value * cartan.axis
        + v_value * cartan.transverse,
        prime,
    )
    block_determinants, gram_determinant = _block_determinants(cartan, frame)
    if gram_determinant == 0:
        return None
    determinant = block_determinants[0] * block_determinants[1] % prime
    return (
        determinant
        * cartan.inverse_base_determinant
        * pow(gram_determinant, -22, prime)
    ) % prime


def _coupled_block_numerator_values(
    system: CoupledModularSystem,
    s_value: int,
    u_value: int,
    v_value: int,
) -> tuple[int, int] | None:
    """Evaluate normalized block numerators of weighted degrees 36 and 48."""

    cartan = system.cartan
    prime = cartan.prime
    frame = np.remainder(
        cartan.frame
        + s_value * system.scalar
        + u_value * cartan.axis
        + v_value * cartan.transverse,
        prime,
    )
    block_determinants, gram_determinant = _block_determinants(cartan, frame)
    if gram_determinant == 0:
        return None
    return tuple(
        determinant * inverse_base * pow(gram_determinant, -exponent, prime) % prime
        for determinant, inverse_base, exponent in zip(
            block_determinants,
            system.inverse_base_block_determinants,
            (10, 12),
            strict=True,
        )
    )


def _direction_pairs(
    prime: int,
    *,
    count: int = RECONSTRUCTION_DIRECTION_COUNT + HOLDOUT_DIRECTION_COUNT,
) -> tuple[tuple[int, int], ...]:
    rng = random.Random(DIRECTION_SEED)
    result: list[tuple[int, int]] = []
    seen: set[tuple[int, int]] = set()
    while len(result) < count:
        pair = (rng.randrange(1, prime), rng.randrange(0, prime))
        if pair not in seen:
            result.append(pair)
            seen.add(pair)
    return tuple(result)


def _direction_invariants(
    pairs: tuple[tuple[int, int], ...],
    system: CoupledModularSystem,
) -> tuple[tuple[int, int], ...]:
    prime = system.cartan.prime
    sqrt2 = system.cartan.sqrt2
    return tuple(
        (
            (3 * u_value**2 + v_value**2) % prime,
            (sqrt2 * u_value * (v_value**2 - u_value**2)) % prime,
        )
        for u_value, v_value in pairs
    )


def _invariant_evaluation_matrix(
    invariants: tuple[tuple[int, int], ...],
    prime: int,
) -> np.ndarray:
    rows: list[list[int]] = []
    maximum_p = max(a for a, _ in MONOMIALS)
    maximum_y = max(b for _, b in MONOMIALS)
    for p_value, y_value in invariants:
        p_powers = [1]
        y_powers = [1]
        for _ in range(maximum_p):
            p_powers.append(p_powers[-1] * p_value % prime)
        for _ in range(maximum_y):
            y_powers.append(y_powers[-1] * y_value % prime)
        rows.append([p_powers[a] * y_powers[b] % prime for a, b in MONOMIALS])
    return np.asarray(rows, dtype=np.int64)


def _safe_scale_nodes(
    invariants: tuple[tuple[int, int], ...],
    system: CoupledModularSystem,
) -> tuple[int, ...]:
    nodes: list[int] = []
    candidate = 0
    prime = system.cartan.prime
    while len(nodes) < SCALE_NODE_COUNT:
        valid = True
        for p_direction, y_direction in invariants:
            p_value = p_direction * candidate**2 % prime
            y_value = y_direction * pow(candidate, 3, prime) % prime
            if _coupled_delta(candidate, p_value, y_value, system) == 0:
                valid = False
                break
        if valid:
            nodes.append(candidate)
        candidate += 1
    return tuple(nodes)


def reconstruct_mod_prime(
    prime: int,
    *,
    sqrt2: int | None = None,
) -> tuple[int, ...]:
    """Reconstruct all 18,600 coupled coefficients modulo one prime."""

    system = _build_coupled_system(prime, sqrt2=sqrt2)
    inverse_sqrt2 = pow(system.cartan.sqrt2, -1, prime)
    pairs = _direction_pairs(prime)
    invariants = _direction_invariants(pairs, system)
    direction_matrix = _invariant_evaluation_matrix(
        invariants[:RECONSTRUCTION_DIRECTION_COUNT],
        prime,
    )
    direction_inverse = _modular_inverse(direction_matrix, prime)

    nodes = _safe_scale_nodes(invariants, system)
    vandermonde = np.asarray(
        [
            [pow(node, degree, prime) for degree in range(SCALE_NODE_COUNT)]
            for node in nodes
        ],
        dtype=np.int64,
    )
    vandermonde_inverse = _modular_inverse(vandermonde, prime)

    values = np.empty((len(pairs), SCALE_NODE_COUNT), dtype=np.int64)
    for direction, (u_direction, v_direction) in enumerate(pairs):
        for node_index, scale in enumerate(nodes):
            value = _coupled_numerator_value(
                system,
                inverse_sqrt2 * scale,
                u_direction * scale,
                v_direction * scale,
            )
            if value is None:
                raise AssertionError("safe-node selection admitted a Gram pole")
            values[direction, node_index] = value
    line_coefficients = np.remainder(vandermonde_inverse @ values.T, prime).T
    coefficient_table = np.remainder(
        direction_inverse @ line_coefficients[:RECONSTRUCTION_DIRECTION_COUNT],
        prime,
    )

    result: list[int] = []
    invalid_nonzero = 0
    for weight in range(WEIGHTED_DEGREE + 1):
        for monomial_index, (a, b) in enumerate(MONOMIALS):
            scalar_power = weight - 2 * a - 3 * b
            value = int(coefficient_table[monomial_index, weight])
            if scalar_power < 0:
                invalid_nonzero += value != 0
            else:
                result.append(value)
    if invalid_nonzero:
        raise AssertionError(
            f"{invalid_nonzero} coefficients violate weighted degree 84"
        )

    maximum_p = max(a for a, _ in MONOMIALS)
    maximum_y = max(b for _, b in MONOMIALS)
    for direction in range(
        RECONSTRUCTION_DIRECTION_COUNT,
        len(pairs),
    ):
        p_value, y_value = invariants[direction]
        p_powers = [1]
        y_powers = [1]
        for _ in range(maximum_p):
            p_powers.append(p_powers[-1] * p_value % prime)
        for _ in range(maximum_y):
            y_powers.append(y_powers[-1] * y_value % prime)
        for weight in range(WEIGHTED_DEGREE + 1):
            predicted = 0
            for monomial_index, (a, b) in enumerate(MONOMIALS):
                if 2 * a + 3 * b <= weight:
                    predicted = (
                        predicted
                        + int(coefficient_table[monomial_index, weight])
                        * p_powers[a]
                        * y_powers[b]
                    ) % prime
            if predicted != int(line_coefficients[direction, weight]):
                raise AssertionError(
                    f"direction holdout failed at ({direction}, {weight})"
                )
    return tuple(result)


def reconstruct_rational_coefficients(
    primes: tuple[int, ...] = RECONSTRUCTION_PRIMES,
    *,
    progress: bool = False,
    workers: int = 1,
) -> tuple[tuple[Fraction, ...], int]:
    """CRT-combine prime images and recover rational coefficients."""

    combined = [0] * len(COUPLED_MONOMIALS)
    modulus = 1
    if workers < 1:
        raise ValueError("workers must be positive")
    if workers == 1:
        residue_tables = map(reconstruct_mod_prime, primes)
    else:
        if progress:
            print(
                f"dispatching {len(primes)} primes across {workers} workers",
                file=sys.stderr,
                flush=True,
            )
        executor = ProcessPoolExecutor(max_workers=workers)
        residue_tables = executor.map(reconstruct_mod_prime, primes)
    try:
        indexed_tables = enumerate(zip(primes, residue_tables, strict=True), start=1)
        for index, (prime, residues) in indexed_tables:
            if progress:
                print(
                    f"coupled reconstruction prime {index}/{len(primes)}: {prime}",
                    file=sys.stderr,
                    flush=True,
                )
            correction_inverse = pow(modulus % prime, -1, prime)
            for coefficient_index, residue in enumerate(residues):
                correction = (
                    (residue - combined[coefficient_index]) % prime * correction_inverse
                ) % prime
                combined[coefficient_index] += modulus * correction
            modulus *= prime
    finally:
        if workers != 1:
            executor.shutdown()

    rational = tuple(_rational_reconstruction(value, modulus) for value in combined)
    if any(value is None for value in rational):
        missing = sum(value is None for value in rational)
        raise ValueError(
            f"{missing} coefficients exceed the rational reconstruction bound"
        )
    return tuple(value for value in rational if value is not None), modulus


def validate_rational_coefficients(
    coefficients: tuple[Fraction, ...],
    prime: int = VALIDATION_PRIME,
) -> bool:
    recovered = tuple(
        coefficient.numerator * pow(coefficient.denominator, -1, prime) % prime
        for coefficient in coefficients
    )
    positive_root = int(_build_modular_system(prime).sqrt2)
    return all(
        recovered == reconstruct_mod_prime(prime, sqrt2=root)
        for root in (positive_root, (-positive_root) % prime)
    )


def _v5_boundary_check(coefficients: tuple[Fraction, ...]) -> bool:
    maintained = load_v5_coefficients(DEFAULT_V5_ARTIFACT)
    coupled = {
        (p_power, y_power): value
        for (x_power, p_power, y_power), value in zip(
            COUPLED_MONOMIALS,
            coefficients,
            strict=True,
        )
        if x_power == 0
    }
    return all(
        coupled[(p_power, y_power)] == value
        for (p_power, y_power), value in zip(MONOMIALS, maintained, strict=True)
    )


def _multiply_polynomials(left: list[int], right: list[int]) -> list[int]:
    result = [0] * (len(left) + len(right) - 1)
    for left_degree, left_coefficient in enumerate(left):
        for right_degree, right_coefficient in enumerate(right):
            result[left_degree + right_degree] += left_coefficient * right_coefficient
    return result


def _power_polynomial(polynomial: list[int], exponent: int) -> list[int]:
    result = [1]
    factor = polynomial
    while exponent:
        if exponent & 1:
            result = _multiply_polynomials(result, factor)
        exponent >>= 1
        if exponent:
            factor = _multiply_polynomials(factor, factor)
    return result


def _v1_boundary_check(coefficients: tuple[Fraction, ...]) -> bool:
    """Check the maintained symmetric-curve formula at p=y=0."""

    factors = (
        ([1, -4, 0, 8, 4], 10),
        ([1, 8, 12, -16, 4], 3),
        ([1, 2, 6, -4, 4], 5),
        ([1, 0, 2], 6),
    )
    expected = [1]
    for polynomial, exponent in factors:
        expected = _multiply_polynomials(
            expected,
            _power_polynomial(polynomial, exponent),
        )
    observed = {
        x_power: value
        for (x_power, p_power, y_power), value in zip(
            COUPLED_MONOMIALS,
            coefficients,
            strict=True,
        )
        if p_power == 0 and y_power == 0
    }
    return len(expected) == WEIGHTED_DEGREE + 1 and all(
        observed[degree] == coefficient for degree, coefficient in enumerate(expected)
    )


def coefficient_payload(
    coefficients: tuple[Fraction, ...],
    modulus: int,
) -> dict[str, object]:
    rows = [
        {
            "x_power": x_power,
            "p_power": p_power,
            "y_power": y_power,
            "coefficient": str(coefficient),
        }
        for (x_power, p_power, y_power), coefficient in zip(
            COUPLED_MONOMIALS,
            coefficients,
            strict=True,
        )
    ]
    canonical = "\n".join(
        f"{row['x_power']},{row['p_power']},{row['y_power']}:{row['coefficient']}"
        for row in rows
    )
    unused_prime_valid = validate_rational_coefficients(coefficients)
    v5_boundary_valid = _v5_boundary_check(coefficients)
    v1_boundary_valid = _v1_boundary_check(coefficients)
    return {
        "schema_version": 1,
        "claim_scope": "modular reconstruction on the coupled V1+V5 Cartan slice",
        "invariants": {
            "x": "sqrt(2)*s",
            "x_weight": 1,
            "p": "3*u^2+v^2",
            "p_weight": 2,
            "y": "sqrt(2)*u*(v^2-u^2)",
            "y_weight": 3,
            "gram_determinant": (
                "1+8*p+20*p^2+16*p^3-16*y^2+6*x^2+24*x^2*p+"
                "8*x^2*p^2+12*x^4+16*x^4*p+8*x^6+24*x*y+"
                "80*x*p*y+80*x^3*y"
            ),
            "determinant_ratio_form": "N(x,p,y)/gram_determinant^14",
        },
        "weighted_degree": WEIGHTED_DEGREE,
        "coefficient_count": len(coefficients),
        "nonzero_coefficient_count": sum(value != 0 for value in coefficients),
        "all_coefficients_integral": all(
            value.denominator == 1 for value in coefficients
        ),
        "maximum_numerator_digits": max(
            len(str(abs(value.numerator))) for value in coefficients
        ),
        "reconstruction_direction_count": RECONSTRUCTION_DIRECTION_COUNT,
        "holdout_direction_count": HOLDOUT_DIRECTION_COUNT,
        "scale_node_count": SCALE_NODE_COUNT,
        "weighted_degree_zero_constraints_per_prime": (
            len(MONOMIALS) * SCALE_NODE_COUNT - len(COUPLED_MONOMIALS)
        ),
        "direction_holdout_constraints_per_prime": (
            HOLDOUT_DIRECTION_COUNT * SCALE_NODE_COUNT
        ),
        "reconstruction_primes": list(RECONSTRUCTION_PRIMES),
        "crt_modulus": str(modulus),
        "crt_modulus_decimal_digits": len(str(modulus)),
        "unused_validation_prime": VALIDATION_PRIME,
        "unused_prime_both_sqrt2_embeddings_passed": unused_prime_valid,
        "pure_v1_boundary_identity_passed": v1_boundary_valid,
        "pure_v5_boundary_identity_passed": v5_boundary_valid,
        "coefficient_rows_sha256": hashlib.sha256(canonical.encode()).hexdigest(),
        "coefficients": rows,
        "characteristic_zero_identity_certified": False,
        "global_coupled_positivity_certified": False,
        "passed": bool(unused_prime_valid and v1_boundary_valid and v5_boundary_valid),
    }


def load_coefficients(path: Path) -> tuple[Fraction, ...]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    rows = payload["coefficients"]
    if len(rows) != len(COUPLED_MONOMIALS):
        raise ValueError("coupled coefficient artifact has the wrong row count")
    result: list[Fraction] = []
    canonical_rows: list[str] = []
    for monomial, row in zip(COUPLED_MONOMIALS, rows, strict=True):
        observed = (row["x_power"], row["p_power"], row["y_power"])
        if observed != monomial:
            raise ValueError("coupled coefficient monomial order mismatch")
        result.append(Fraction(row["coefficient"]))
        canonical_rows.append(
            f"{row['x_power']},{row['p_power']},{row['y_power']}:{row['coefficient']}"
        )
    digest = hashlib.sha256("\n".join(canonical_rows).encode()).hexdigest()
    if digest != payload["coefficient_rows_sha256"]:
        raise ValueError("coupled coefficient artifact digest mismatch")
    return tuple(result)


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, help="optional reconstruction JSON")
    parser.add_argument(
        "--workers",
        type=int,
        default=1,
        help="independent prime reconstructions to run concurrently",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="write the artifact without echoing its full JSON payload",
    )
    return parser.parse_args()


def main() -> int:
    args = _parse_args()
    coefficients, modulus = reconstruct_rational_coefficients(
        progress=True,
        workers=args.workers,
    )
    payload = coefficient_payload(coefficients, modulus)
    encoded = json.dumps(payload, indent=2, sort_keys=True)
    if args.output is not None:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(encoded + "\n", encoding="utf-8")
    if not args.quiet:
        print(encoded)
    else:
        print(
            f"coupled reconstruction passed={payload['passed']} "
            f"coefficients={payload['coefficient_count']}",
            file=sys.stderr,
        )
    return 0 if payload["passed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
