"""Characteristic-zero lift for the coupled Spin(9) ``V1 + V5`` slice.

The raw determinant identity has total degree at most 216 and is invariant
under the stabilizer action on ``V1 + Sym_0(3)``.  Its invariant ring is
generated by ``x, p, y`` of weights ``1, 2, 3``.  This module validates the
identity over both embeddings of ``sqrt(2)`` in enough prime fields, using a
graded unisolvent direction cover, and lifts it to characteristic zero with
an explicit coefficient bound.

The graded direction cover is intentionally smaller than a rectangular
three-variable interpolation grid.  Once weights through ``d`` have vanished,
a new direction needs only ``216-d`` nonzero scale samples.  Prefix direction
matrices are checked for full rank at every twelve-weight gate.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import random
import struct
import sys
from array import array
from concurrent.futures import ProcessPoolExecutor, as_completed
from functools import lru_cache
from pathlib import Path

import sympy as sp
from flint import nmod_mat

from spin9_dirac_clifford import build_spin9_clifford_system
from spin9_v1_v5_boundary_char0 import _base_and_variations
from spin9_v1_v5_reconstruction import (
    COUPLED_INFORMATION_BLOCKS,
    COUPLED_MONOMIALS,
    ROOT,
    _block_determinants,
    _build_coupled_system,
    _coupled_delta,
    load_coefficients,
)
from spin9_v5_cartan_reconstruction import IDENTITY_PRIMES

SQRT2 = sp.sqrt(2)
S, U, V = sp.symbols("s u v", real=True)
IDENTITY_DEGREE = 216
DIRECTION_STEP = 12
DIRECTION_SEED = 20_260_812
SHAPE_MONOMIALS = tuple(
    (a, b)
    for weight in range(IDENTITY_DEGREE + 1)
    for b in range(IDENTITY_DEGREE // 3 + 1)
    for a in range(IDENTITY_DEGREE // 2 + 1)
    if 2 * a + 3 * b == weight
)
SHAPE_INDEX = {monomial: index for index, monomial in enumerate(SHAPE_MONOMIALS)}
NUMERATOR_SHAPE_COUNT = sum(
    2 * a + 3 * b <= 84 for a, b in SHAPE_MONOMIALS
)
WEIGHT_GATES = tuple(range(DIRECTION_STEP, IDENTITY_DEGREE + 1, DIRECTION_STEP))
DEFAULT_COEFFICIENT_ARTIFACT = (
    ROOT / "artifacts" / "spin9_v1_v5_reconstruction_20260811.json"
)
DEFAULT_OUTPUT = ROOT / "artifacts" / "spin9_v1_v5_char0_20260812.json"


def _next_identity_primes(count: int) -> tuple[int, ...]:
    """Return deterministic 8-digit primes in which two is a square."""

    result = list(IDENTITY_PRIMES)
    candidate = result[-1] + 1
    while len(result) < count:
        candidate = int(sp.nextprime(candidate))
        if sp.legendre_symbol(2, candidate) == 1:
            result.append(candidate)
        candidate += 1
    return tuple(result)


@lru_cache(maxsize=1)
def _exact_information_matrix() -> sp.Matrix:
    """Build the raw coupled information numerator over ``QQ(sqrt(2))``."""

    base, scalar, axis, transverse = _base_and_variations()
    frame = base + S * scalar + U * axis + V * transverse
    gram_adjugate = (frame.T * frame).adjugate()
    generators = tuple(
        sp.Matrix(matrix)
        for matrix in build_spin9_clifford_system().doubled_spin_generators
    )
    observations = tuple(
        sp.Matrix.hstack(
            *(generator * frame[:, column] for generator in generators)
        ).T
        for column in range(3)
    )
    information = sp.zeros(36)
    for left in range(3):
        for right in range(3):
            information += (
                gram_adjugate[left, right]
                * observations[left]
                * observations[right].T
            )
    return information.applyfunc(sp.expand)


def _quadratic_norm(value: sp.Expr) -> sp.Rational:
    expanded = sp.expand(value)
    rational = sp.Rational(expanded.coeff(SQRT2, 0))
    radical = sp.Rational(expanded.coeff(SQRT2, 1))
    if sp.expand(rational + radical * SQRT2 - expanded) != 0:
        raise AssertionError("coefficient escaped QQ(sqrt(2))")
    return abs(rational) + 2 * abs(radical)


def _polynomial_l1(value: sp.Expr) -> sp.Rational:
    polynomial = sp.Poly(value, S, U, V, extension=SQRT2)
    return sum((_quadratic_norm(coefficient) for coefficient in polynomial.coeffs()), sp.Rational(0))


def coefficient_bound_certificate(
    coefficients: tuple[sp.Rational, ...] | tuple[object, ...],
) -> dict[str, object]:
    """Return a rigorous coefficient bound for the raw identity residual."""

    information = _exact_information_matrix()
    first_block, second_block = COUPLED_INFORMATION_BLOCKS
    cross_block = information.extract(first_block, second_block)
    if cross_block != sp.zeros(len(first_block), len(second_block)):
        raise AssertionError("coupled information blocks are not exact")
    if any(
        sp.Poly(entry, S, U, V, extension=SQRT2).total_degree() > 6
        for entry in information
    ):
        raise AssertionError("coupled information entry degree exceeds six")
    row_norms = tuple(
        sum((_polynomial_l1(information[row, column]) for column in range(36)), sp.Rational(0))
        for row in range(36)
    )
    denominators = {value.q for value in row_norms}
    if denominators != {1}:
        raise AssertionError("coupled information row norms are not integral")
    integer_row_norms = tuple(int(value) for value in row_norms)
    determinant_bound = math.prod(integer_row_norms)

    base_information = information.subs({S: 0, U: 0, V: 0})
    base_determinants = tuple(
        int(
            base_information.extract(block, block).det(method="domain-ge")
        )
        for block in COUPLED_INFORMATION_BLOCKS
    )
    if base_determinants != (65_536, 262_144):
        raise AssertionError("base block determinants changed")
    base_product = math.prod(base_determinants)

    x_norm = 2
    p_norm = 4
    y_norm = 4
    numerator_bound = sum(
        abs(int(coefficient.numerator))
        * x_norm**x_power
        * p_norm**p_power
        * y_norm**y_power
        for (x_power, p_power, y_power), coefficient in zip(
            COUPLED_MONOMIALS,
            coefficients,
            strict=True,
        )
    )
    delta_bound = (
        1
        + 8 * p_norm
        + 20 * p_norm**2
        + 16 * p_norm**3
        + 16 * y_norm**2
        + 6 * x_norm**2
        + 24 * x_norm**2 * p_norm
        + 8 * x_norm**2 * p_norm**2
        + 12 * x_norm**4
        + 16 * x_norm**4 * p_norm
        + 8 * x_norm**6
        + 24 * x_norm * y_norm
        + 80 * x_norm * p_norm * y_norm
        + 80 * x_norm**3 * y_norm
    )
    candidate_bound = base_product * delta_bound**22 * numerator_bound
    residual_bound = determinant_bound + candidate_bound

    prime_count = len(IDENTITY_PRIMES)
    while math.prod(_next_identity_primes(prime_count)) <= 2 * residual_bound:
        prime_count += 1
    primes = _next_identity_primes(prime_count)
    modulus = math.prod(primes)
    return {
        "coefficient_norm": "l1 with |a+b*sqrt(2)|_q=|a|+2|b|",
        "information_row_l1_norms": list(integer_row_norms),
        "determinant_coefficient_bound": str(determinant_bound),
        "base_information_block_determinants": list(base_determinants),
        "substituted_invariant_norm_bounds": {"x": x_norm, "p": p_norm, "y": y_norm},
        "substituted_delta_norm_bound": delta_bound,
        "candidate_numerator_norm_bound": str(numerator_bound),
        "candidate_rhs_coefficient_bound": str(candidate_bound),
        "residual_coefficient_bound": str(residual_bound),
        "identity_primes": list(primes),
        "identity_prime_product": str(modulus),
        "identity_prime_product_digits": len(str(modulus)),
        "prime_product_exceeds_twice_residual_bound": modulus > 2 * residual_bound,
        "information_entries_in_Z_sqrt2": True,
    }


@lru_cache(maxsize=1)
def _direction_pairs() -> tuple[tuple[int, int], ...]:
    rng = random.Random(DIRECTION_SEED)
    result: list[tuple[int, int]] = []
    seen: set[tuple[int, int]] = set()
    while len(result) < len(SHAPE_MONOMIALS):
        pair = (rng.randrange(1, 10_000_000), rng.randrange(0, 10_000_000))
        if pair not in seen:
            result.append(pair)
            seen.add(pair)
    return tuple(result)


def _shape_rows(
    prime: int,
    sqrt2: int,
) -> array[int]:
    rows = array("I")
    maximum_p = max(a for a, _ in SHAPE_MONOMIALS)
    maximum_y = max(b for _, b in SHAPE_MONOMIALS)
    for u_value, v_value in _direction_pairs():
        p_value = (3 * u_value**2 + v_value**2) % prime
        y_value = (sqrt2 * u_value * (v_value**2 - u_value**2)) % prime
        p_powers = [1]
        y_powers = [1]
        for _ in range(maximum_p):
            p_powers.append(p_powers[-1] * p_value % prime)
        for _ in range(maximum_y):
            y_powers.append(y_powers[-1] * y_value % prime)
        rows.extend(
            p_powers[a] * y_powers[b] % prime for a, b in SHAPE_MONOMIALS
        )
    return rows


def _gate_direction_counts() -> tuple[int, ...]:
    return tuple(
        sum(2 * a + 3 * b <= gate for a, b in SHAPE_MONOMIALS)
        for gate in WEIGHT_GATES
    )


def _rank_certificate(
    rows: array[int],
    prime: int,
) -> list[dict[str, int]]:
    result: list[dict[str, int]] = []
    for gate, count in zip(WEIGHT_GATES, _gate_direction_counts(), strict=True):
        entries = array("I")
        width = len(SHAPE_MONOMIALS)
        for row in range(count):
            start = row * width
            entries.extend(rows[start : start + count])
        matrix = nmod_mat(count, count, entries, prime)
        rank = matrix.rank()
        result.append({"maximum_weight": gate, "direction_count": count, "rank": rank})
        if rank != count:
            raise AssertionError(f"direction prefix lost rank at weight {gate}")
    return result


def _coefficient_table(
    coefficients: tuple[object, ...],
    prime: int,
) -> nmod_mat:
    values = array("I", [0]) * (NUMERATOR_SHAPE_COUNT * 85)
    for monomial, coefficient in zip(COUPLED_MONOMIALS, coefficients, strict=True):
        x_power, p_power, y_power = monomial
        weight = x_power + 2 * p_power + 3 * y_power
        row = SHAPE_INDEX[(p_power, y_power)]
        values[row * 85 + weight] = int(coefficient.numerator) % prime
    return nmod_mat(NUMERATOR_SHAPE_COUNT, 85, values, prime)


def _line_coefficients(
    rows: array[int],
    coefficients: tuple[object, ...],
    prime: int,
) -> list[list[int]]:
    entries = array("I")
    width = len(SHAPE_MONOMIALS)
    for row in range(width):
        start = row * width
        entries.extend(rows[start : start + NUMERATOR_SHAPE_COUNT])
    evaluation = nmod_mat(width, NUMERATOR_SHAPE_COUNT, entries, prime)
    return (evaluation * _coefficient_table(coefficients, prime)).tolist()


def _horner(coefficients: list[int], value: int, prime: int) -> int:
    result = 0
    for coefficient in reversed(coefficients):
        result = (result * value + int(coefficient)) % prime
    return result


def validate_identity_mod_prime(
    task: tuple[int, tuple[object, ...]],
) -> dict[str, object]:
    """Validate the complete raw identity over one prime and both embeddings."""

    prime, coefficients = task
    positive_root = int(sp.sqrt_mod(2, prime))
    positive_rows = _shape_rows(prime, positive_root)
    ranks = _rank_certificate(positive_rows, prime)
    counts = _gate_direction_counts()
    base_product = (65_536 * 262_144) % prime
    point_count = 0
    digest = hashlib.sha256()
    embedding_rows: list[dict[str, object]] = []

    for root in (positive_root, (-positive_root) % prime):
        rows = positive_rows if root == positive_root else _shape_rows(prime, root)
        line_rows = _line_coefficients(rows, coefficients, prime)
        system = _build_coupled_system(prime, sqrt2=root)
        inverse_root = pow(root, -1, prime)
        previous_count = 0
        previous_gate = -1
        embedding_points = 0
        for gate, direction_count in zip(WEIGHT_GATES, counts, strict=True):
            scale_count = IDENTITY_DEGREE - previous_gate
            for direction_index in range(previous_count, direction_count):
                u_direction, v_direction = _direction_pairs()[direction_index]
                p_direction = (3 * u_direction**2 + v_direction**2) % prime
                y_direction = (
                    root
                    * u_direction
                    * (v_direction**2 - u_direction**2)
                ) % prime
                for scale in range(1, scale_count + 1):
                    s_value = inverse_root * scale % prime
                    u_value = u_direction * scale % prime
                    v_value = v_direction * scale % prime
                    frame = (
                        system.cartan.frame
                        + s_value * system.scalar
                        + u_value * system.cartan.axis
                        + v_value * system.cartan.transverse
                    ) % prime
                    block_determinants, gram_determinant = _block_determinants(
                        system.cartan,
                        frame,
                    )
                    raw = block_determinants[0] * block_determinants[1] % prime
                    p_value = p_direction * scale**2 % prime
                    y_value = y_direction * scale**3 % prime
                    delta = _coupled_delta(scale, p_value, y_value, system)
                    numerator = _horner(line_rows[direction_index], scale, prime)
                    expected = (
                        base_product * pow(delta, 22, prime) * numerator
                    ) % prime
                    digest.update(struct.pack("<II", raw, expected))
                    if raw != expected or gram_determinant != delta:
                        return {
                            "prime": prime,
                            "passed": False,
                            "failure": {
                                "root": root,
                                "direction_index": direction_index,
                                "scale": scale,
                            },
                        }
                    embedding_points += 1
            previous_count = direction_count
            previous_gate = gate
        point_count += embedding_points
        embedding_rows.append(
            {"sqrt2_root": root, "raw_point_count": embedding_points, "passed": True}
        )
    return {
        "prime": prime,
        "direction_seed": DIRECTION_SEED,
        "graded_rank_gates": ranks,
        "embeddings": embedding_rows,
        "raw_point_count": point_count,
        "raw_rows_sha256": digest.hexdigest(),
        "passed": True,
    }


def certificate(
    coefficient_artifact: Path = DEFAULT_COEFFICIENT_ARTIFACT,
    *,
    workers: int = 1,
    prime_limit: int | None = None,
) -> dict[str, object]:
    """Replay the characteristic-zero lift and return its proof artifact."""

    if workers < 1:
        raise ValueError("workers must be positive")
    coefficients = load_coefficients(coefficient_artifact)
    bound = coefficient_bound_certificate(coefficients)
    primes = tuple(bound["identity_primes"])
    if prime_limit is not None:
        primes = primes[:prime_limit]
    tasks = tuple((prime, coefficients) for prime in primes)
    if workers == 1:
        rows = []
        for index, task in enumerate(tasks, start=1):
            print(f"identity prime {index}/{len(tasks)}: {task[0]}", file=sys.stderr, flush=True)
            rows.append(validate_identity_mod_prime(task))
    else:
        with ProcessPoolExecutor(max_workers=workers) as executor:
            futures = {
                executor.submit(validate_identity_mod_prime, task): task[0]
                for task in tasks
            }
            rows = []
            for index, future in enumerate(as_completed(futures), start=1):
                row = future.result()
                rows.append(row)
                print(
                    f"identity prime {index}/{len(tasks)} complete: "
                    f"{row['prime']}",
                    file=sys.stderr,
                    flush=True,
                )
            rows.sort(key=lambda row: row["prime"])
    full_prime_set = len(primes) == len(bound["identity_primes"])
    passed = bool(
        full_prime_set
        and all(row["passed"] for row in rows)
        and bound["prime_product_exceeds_twice_residual_bound"]
    )
    return {
        "schema_version": 1,
        "claim_scope": "raw characteristic-zero identity on the coupled V1+V5 Cartan slice",
        "arithmetic_field": "ZZ[sqrt(2)]",
        "invariant_ring": "QQ[x,p,y], weights (1,2,3)",
        "raw_identity": "det(J16)*det(J20)=65536*262144*delta^22*N(x,p,y)",
        "raw_total_degree_bound": IDENTITY_DEGREE,
        "graded_direction_method": {
            "weight_step": DIRECTION_STEP,
            "maximum_direction_count": len(SHAPE_MONOMIALS),
            "direction_seed": DIRECTION_SEED,
            "induction": (
                "after lower weights vanish, each new direction uses only the "
                "remaining nonzero scale nodes"
            ),
        },
        "coefficient_artifact": coefficient_artifact.name,
        "coefficient_bound": bound,
        "prime_rows": rows,
        "full_required_prime_set_checked": full_prime_set,
        "characteristic_zero_identity_certified": passed,
        "passed": passed,
    }


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--coefficients", type=Path, default=DEFAULT_COEFFICIENT_ARTIFACT)
    parser.add_argument("--workers", type=int, default=1)
    parser.add_argument("--prime-limit", type=int)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    return parser.parse_args()


def main() -> int:
    arguments = _parse_args()
    report = certificate(
        arguments.coefficients,
        workers=arguments.workers,
        prime_limit=arguments.prime_limit,
    )
    encoded = json.dumps(report, indent=2, sort_keys=True)
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(encoded + "\n", encoding="utf-8")
    print(encoded)
    return 0 if report["passed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
